export type Language = "en" | "es" | "fr" | "de" | "it" | "pt" | "ja" | "zh" | "ru" | "ar"

export const languageLabels: Record<Language, string> = {
  en: "Inglés",
  es: "Español",
  fr: "Francés",
  de: "Alemán",
  it: "Italiano",
  pt: "Portugués",
  ja: "Japonés",
  zh: "Chino",
  ru: "Ruso",
  ar: "Árabe",
}

const english: Record<string, string> = {
  dashboard: "Dashboard",
  trade: "Trade",
  markets: "Markets",
  history: "History",
  wallet: "Wallet",
  learn: "Learn",
  "hint-dashboard": "Your main trading overview",
  "hint-trade": "Open and manage trades",
  "hint-markets": "Browse all currency pairs",
  "hint-history": "View your past trades",
  "hint-wallet": "Manage your funds",
  "hint-learn": "Tutorials and guides",
  logout: "Logout",
  settings: "Settings",
  notifications: "Notifications",
  help: "Help",
  "coming-soon": "Coming soon",
  loading: "Loading...",
  "no-results": "No results found",
  "total-balance": "Total Balance",
  "total-profit": "Total Profit",
  "open-positions": "Open Positions",
  "available-margin": "Available Margin",
  "place-trade": "Place a Trade",
  "practice-mode": "Practice with virtual money",
  "practice-mode-desc": "You're trading with $10,000 virtual money. No real funds at risk - learn freely!",
  "currency-pair": "Currency Pair",
  "trade-size": "Trade Size (Lots)",
  buy: "BUY",
  sell: "SELL",
  "confirm-trade": "Confirm your trade",
  cancel: "Cancel",
  confirm: "Confirm",
  "start-learning": "Start your learning path",
  "lesson-overview": "Lesson Overview",
  "history-log-title": "Your learning log",
  "history-log-desc": "We will list every completed trade with an easy summary.",
  "markets-popular-title": "Popular beginner pairs",
  "markets-popular-desc": "These pairs have reliable liquidity and clear patterns for practice.",
  "wallet-practice-title": "Practice balance",
  "wallet-practice-desc": "This is virtual money you can use to learn safely.",
  "learn-desc": "Follow one short lesson at a time and practice after each one.",
  "getting-started": "Getting Started",
  "trading-basics": "Trading Basics",
  "simple-strategies": "Simple Strategies",
  "help.article.getting-started.0.title": "What is forex trading?",
  "help.article.getting-started.0.time": "3 min read",
  "help.article.getting-started.1.title": "Understanding currency pairs",
  "help.article.getting-started.1.time": "4 min read",
  "help.article.getting-started.2.title": "How to read a price chart",
  "help.article.getting-started.2.time": "5 min read",
  "help.article.getting-started.3.title": "Your first practice trade",
  "help.article.getting-started.3.time": "3 min read",
  "help.article.trading-basics.0.title": "What are pips and lots?",
  "help.article.trading-basics.0.time": "3 min read",
  "help.article.trading-basics.1.title": "Understanding leverage and margin",
  "help.article.trading-basics.1.time": "5 min read",
  "help.article.trading-basics.2.title": "Setting stop-loss and take-profit",
  "help.article.trading-basics.2.time": "4 min read",
  "help.article.trading-basics.3.title": "Market vs limit orders",
  "help.article.trading-basics.3.time": "3 min read",
  "help.article.strategies.0.title": "Trend following for beginners",
  "help.article.strategies.0.time": "6 min read",
  "help.article.strategies.1.title": "Support and resistance basics",
  "help.article.strategies.1.time": "5 min read",
  "help.article.strategies.2.title": "Risk management 101",
  "help.article.strategies.2.time": "4 min read",
  "faq.title": "Frequently Asked",
  "faq.q.0": "Is this real money?",
  "faq.a.0": "No! You're in practice mode with $10,000 virtual money. Nothing you do here costs real money.",
  "faq.q.1": "What does BUY and SELL mean?",
  "faq.a.1": "BUY (going 'long') means you profit when the price goes UP. SELL (going 'short') means you profit when the price goes DOWN.",
  "faq.q.2": "What's a safe lot size to start?",
  "faq.a.2": "Start with 0.01 lots (micro lot). This minimizes your risk while you learn how trading works.",
  "faq.q.3": "What is spread?",
  "faq.a.3": "The spread is the difference between the buy and sell price. It's essentially the broker's fee for each trade.",
  continue: "Continue",
  "lesson-not-found-title": "Lesson Not Found",
  "lesson-not-found-desc": "This lesson does not exist",
  "lesson-guided-subtitle": "Follow the guided tutorial",
  "back-to-lessons": "Back to Lessons",
  "start-guided-tutorial": "Start Guided Tutorial",
  exit: "Exit",
  next: "Next",
  complete: "Complete",
  step: "Step",
  of: "of",
  "trade-executed": "Trade executed!",
  "trade-closed": "Trade closed successfully",
  "help-title": "Help & Learning",
  "help-description": "New to forex? Check out our beginner guides and tutorials.",
  "search-help-placeholder": "Search help articles...",
  "learning-guides": "Learning Guides",
  "articles-label": "articles",
  "beginner-trader": "Beginner trader",
  "search-placeholder": "Search currency pairs...",
  "markets-open": "Markets Open",
  "language-tooltip": "Select language (English / Español)",
  "help-tooltip": "Get help & tutorials",
  "notifications-tooltip": "Notifications (coming soon)",
  "settings-tooltip": "Settings (coming soon)",
  "switch-to-light": "Switch to light mode",
  "switch-to-dark": "Switch to dark mode",
  "search-coming-soon-title": "Search is coming soon",
  "search-coming-soon-desc": "We're working on adding search functionality for currency pairs.",
  "settings-coming-soon-title": "Settings coming soon",
  "settings-coming-soon-desc": "User settings will be available in the next update.",
  "notifications-coming-soon-title": "Notifications not yet available",
  "notifications-coming-soon-desc": "Real-time notifications feature is under development.",
  "welcome-back": "Welcome back, ",
  "your-trades": "Your Trades",
  "trades-hover-headers": "Hover headers to learn what they mean",
  "trades-active": "active",
  "trades-empty-title": "No trades yet",
  "trades-empty-desc": "Place your first practice trade to see it here",
  "trades-column-pair": "Pair",
  "trades-column-direction": "Direction",
  "trades-column-size": "Size",
  "trades-column-entry": "Entry",
  "trades-column-pnl": "P&L",
  "trades-column-status": "Status",
  "trades-hint-pair": "The two currencies being exchanged. EUR/USD means trading Euros for US Dollars.",
  "trades-hint-direction": "BUY = you profit when price goes UP. SELL = you profit when price goes DOWN.",
  "trades-hint-size": "How much you're trading. 0.01 lots is the smallest — perfect for learning!",
  "trades-hint-entry": "The price when your trade started.",
  "trades-hint-pnl": "Profit & Loss — green means you're making money, red means losing.",
  "trades-hint-status": "Open = trade is still running. Closed = trade is finished.",
  "trades-direction-buy-hint": "You profit if the price goes UP",
  "trades-direction-sell-hint": "You profit if the price goes DOWN",
  "trades-lots": "lots",
  "trades-status-open": "Active",
  "trades-status-closed": "Closed",
  "trades-pnl-title": "Understanding P&L (Profit & Loss)",
  "trades-pnl-desc": "P&L shows how much you have gained or lost on each trade. It is calculated from the difference between your entry price and current price, multiplied by your trade size. With 0.01 lots, each pip is worth about $0.10.",
}

const spanish: Record<string, string> = {
  dashboard: "Panel",
  trade: "Operar",
  markets: "Mercados",
  history: "Historial",
  wallet: "Cartera",
  learn: "Aprender",
  "hint-dashboard": "Tu vista general principal de trading",
  "hint-trade": "Abrir y gestionar operaciones",
  "hint-markets": "Explorar todos los pares de divisas",
  "hint-history": "Ver tus operaciones pasadas",
  "hint-wallet": "Gestionar tus fondos",
  "hint-learn": "Tutoriales y guías",
  logout: "Cerrar sesión",
  settings: "Configuración",
  notifications: "Notificaciones",
  help: "Ayuda",
  "coming-soon": "Próximamente",
  loading: "Cargando...",
  "no-results": "No se encontraron resultados",
  "total-balance": "Saldo Total",
  "total-profit": "Ganancia Total",
  "open-positions": "Posiciones Abiertas",
  "available-margin": "Margen Disponible",
  "place-trade": "Realizar una Operación",
  "practice-mode": "Practica con dinero virtual",
  "practice-mode-desc": "Estás operando con $10,000 virtuales. Sin fondos reales en riesgo - ¡aprende libremente!",
  "currency-pair": "Par de Divisas",
  "trade-size": "Tamaño de la Operación (Lotes)",
  buy: "COMPRAR",
  sell: "VENDER",
  "confirm-trade": "Confirmar tu operación",
  cancel: "Cancelar",
  confirm: "Confirmar",
  "start-learning": "Comienza tu camino de aprendizaje",
  "lesson-overview": "Descripción de la Lección",
  "history-log-title": "Tu registro de aprendizaje",
  "history-log-desc": "Aquí listaremos cada operación completada con un resumen fácil de entender.",
  "markets-popular-title": "Pares populares para principiantes",
  "markets-popular-desc": "Estos pares tienen liquidez confiable y patrones claros para practicar.",
  "wallet-practice-title": "Saldo de práctica",
  "wallet-practice-desc": "Este es dinero virtual que puedes usar para aprender de forma segura.",
  "learn-desc": "Sigue una lección corta a la vez y practica después de cada una.",
  "getting-started": "Comenzar",
  "trading-basics": "Conceptos Básicos",
  "simple-strategies": "Estrategias Simples",
  "help.article.getting-started.0.title": "¿Qué es el trading de forex?",
  "help.article.getting-started.0.time": "3 min",
  "help.article.getting-started.1.title": "Entendiendo los pares de divisas",
  "help.article.getting-started.1.time": "4 min",
  "help.article.getting-started.2.title": "Cómo leer un gráfico de precios",
  "help.article.getting-started.2.time": "5 min",
  "help.article.getting-started.3.title": "Tu primera operación de práctica",
  "help.article.getting-started.3.time": "3 min",
  "help.article.trading-basics.0.title": "¿Qué son los pips y los lotes?",
  "help.article.trading-basics.0.time": "3 min",
  "help.article.trading-basics.1.title": "Entendiendo apalancamiento y margen",
  "help.article.trading-basics.1.time": "5 min",
  "help.article.trading-basics.2.title": "Configurar stop-loss y take-profit",
  "help.article.trading-basics.2.time": "4 min",
  "help.article.trading-basics.3.title": "Ordenes de mercado vs límite",
  "help.article.trading-basics.3.time": "3 min",
  "help.article.strategies.0.title": "Seguir tendencias para principiantes",
  "help.article.strategies.0.time": "6 min",
  "help.article.strategies.1.title": "Conceptos básicos de soporte y resistencia",
  "help.article.strategies.1.time": "5 min",
  "help.article.strategies.2.title": "Gestión de riesgo 101",
  "help.article.strategies.2.time": "4 min",
  "faq.title": "Preguntas Frecuentes",
  "faq.q.0": "¿Es dinero real?",
  "faq.a.0": "No. Estás en modo práctica con $10,000 virtuales. Nada de lo que hagas aquí cuesta dinero real.",
  "faq.q.1": "¿Qué significan BUY y SELL?",
  "faq.a.1": "BUY (ir 'largo') significa que ganas cuando el precio SUBE. SELL (ir 'corto') significa que ganas cuando el precio BAJA.",
  "faq.q.2": "¿Qué tamaño de lote es seguro para empezar?",
  "faq.a.2": "Empieza con 0.01 lotes (micro lote). Esto minimiza el riesgo mientras aprendes cómo funciona el trading.",
  "faq.q.3": "¿Qué es el spread?",
  "faq.a.3": "El spread es la diferencia entre el precio de compra y de venta. Básicamente es la comisión del bróker por cada operación.",
  continue: "Continuar",
  "lesson.forex-basics.title": "Conceptos Básicos de Forex",
  "lesson.forex-basics.description": "Entiende cómo se mueven los pares de divisas.",
  "lesson.forex-basics.fullDescription":
    "En esta lección aprenderás los fundamentos del trading de forex, incluyendo pares de divisas, pips y cómo se mueven los precios en el mercado.",
  "lesson.forex-basics.steps.0.title": "¿Qué es Forex?",
  "lesson.forex-basics.steps.0.description":
    "Forex es el mercado de intercambio de divisas donde se compran y venden monedas. Cada operación implica comprar una divisa y vender otra, como EUR/USD.",
  "lesson.forex-basics.steps.0.action": "Haz clic en la sección Mercados para ver pares de divisas en vivo",
  "lesson.forex-basics.steps.1.title": "Explicación de Pares de Divisas",
  "lesson.forex-basics.steps.1.description":
    "Los pares de divisas siempre tienen dos partes: la divisa base (primera) y la divisa cotizada (segunda). Por ejemplo, en EUR/USD, EUR es la base y USD es la cotizada.",
  "lesson.forex-basics.steps.1.action": "Observa cómo cada precio muestra el formato base/cotizada",
  "lesson.forex-basics.steps.2.title": "Entendiendo los Pips",
  "lesson.forex-basics.steps.2.description":
    "Un pip es el movimiento mínimo de precio en forex. La mayoría de los pares se mueven en incrementos de 0.0001 (4 decimales). Un pip = 0.0001 para la mayoría de los pares.",
  "lesson.forex-basics.steps.2.action": "Mira cómo cambian los precios en pequeños incrementos durante el horario del mercado",
  "lesson.forex-basics.steps.3.title": "Precios Bid y Ask",
  "lesson.forex-basics.steps.3.description":
    "Cada cotización tiene un precio bid (lo que quieren los vendedores) y un precio ask (lo que quieren los compradores). Cuando compras, pagas el ask. Cuando vendes, recibes el bid.",
  "lesson.forex-basics.steps.3.action": "Recuerda: siempre compra al ask y vende al bid",
  "lesson.risk-control.title": "Control de Riesgo",
  "lesson.risk-control.description": "Aprende a proteger tu saldo.",
  "lesson.risk-control.fullDescription":
    "Descubre los principios esenciales de la gestión de riesgo para proteger tu cuenta de trading y maximizar la rentabilidad a largo plazo.",
  "lesson.risk-control.steps.0.title": "La Regla del 1%",
  "lesson.risk-control.steps.0.description":
    "Nunca arriesgues más del 1% del saldo de tu cuenta en una sola operación.",
  "lesson.risk-control.steps.0.action": "Calcula: si tienes $10,000, no arriesgues más de $100 por operación",
  "lesson.risk-control.steps.1.title": "Tamaño de Lote",
  "lesson.risk-control.steps.1.description":
    "El tamaño de tu lote determina cuánto dinero está en riesgo. Empieza con 0.01 lotes.",
  "lesson.risk-control.steps.1.action": "Prueba una operación de 0.01 lotes para ver cómo se calcula el riesgo",
  "lesson.risk-control.steps.2.title": "Órdenes Stop Loss",
  "lesson.risk-control.steps.2.description":
    "Siempre establece un stop loss antes de entrar en una operación. Esto cierra tu posición automáticamente si el precio se mueve en tu contra más allá de tu tolerancia al riesgo.",
  "lesson.risk-control.steps.2.action": "En la sección Operar, revisa el campo stop loss antes de ejecutar",
  "lesson.risk-control.steps.3.title": "Relación Riesgo/Recompensa",
  "lesson.risk-control.steps.3.description":
    "Apunta a una relación riesgo/recompensa de 1:2 o mejor.",
  "lesson.risk-control.steps.3.action": "Planifica tus operaciones con buena relación riesgo/recompensa antes de entrar",
  "lesson.reading-charts.title": "Leer Gráficos",
  "lesson.reading-charts.description": "Detecta tendencias con visuales simples.",
  "lesson.reading-charts.fullDescription":
    "Aprende a interpretar los gráficos de precios e identificar tendencias del mercado para tomar decisiones de trading informadas.",
  "lesson.reading-charts.steps.0.title": "Tipos de Gráficos",
  "lesson.reading-charts.steps.0.description":
    "Los gráficos de velas muestran apertura, máximo, mínimo y cierre de cada periodo.",
  "lesson.reading-charts.steps.0.action": "Cambia entre gráficos para ver cómo cambia la lectura del mercado",
  "lesson.reading-charts.steps.1.title": "Identificar Tendencias",
  "lesson.reading-charts.steps.1.description":
    "Una tendencia alcista forma máximos y mínimos crecientes. Una tendencia bajista forma máximos y mínimos decrecientes.",
  "lesson.reading-charts.steps.1.action": "Busca una secuencia clara de máximos y mínimos en el gráfico",
  "lesson.reading-charts.steps.2.title": "Soporte y Resistencia",
  "lesson.reading-charts.steps.2.description":
    "El soporte es un nivel donde el precio suele detenerse al bajar. La resistencia es donde suele frenarse al subir.",
  "lesson.reading-charts.steps.2.action": "Traza mentalmente zonas donde el precio rebota varias veces",
  "lesson.reading-charts.steps.3.title": "Patrones de Velas",
  "lesson.reading-charts.steps.3.description":
    "Algunas formaciones de velas pueden sugerir continuación o cambio de tendencia.",
  "lesson.reading-charts.steps.3.action": "Observa cómo una sola vela puede cambiar el sesgo del mercado",
  "lesson.candlestick-patterns.title": "Patrones de Velas",
  "lesson.candlestick-patterns.description": "Reconoce señales de acción del precio.",
  "lesson.candlestick-patterns.fullDescription":
    "Los patrones de velas ayudan a leer la psicología del mercado y posibles cambios de dirección.",
  "lesson.support-resistance.title": "Soporte y Resistencia",
  "lesson.support-resistance.description": "Encuentra niveles de precio importantes.",
  "lesson.support-resistance.fullDescription":
    "Aprende a identificar niveles clave donde el precio tiende a detenerse o revertirse.",
  "lesson.lot-sizes.title": "Tamaños de Lote",
  "lesson.lot-sizes.description": "Controla el tamaño de tu posición.",
  "lesson.lot-sizes.fullDescription":
    "Descubre cómo el tamaño del lote afecta tu riesgo, exposición y consistencia al operar.",
  "lesson-not-found-title": "Lección No Encontrada",
  "lesson-not-found-desc": "Esta lección no existe",
  "lesson-guided-subtitle": "Sigue el tutorial guiado",
  "back-to-lessons": "Volver a Lecciones",
  "start-guided-tutorial": "Iniciar Tutorial Guiado",
  exit: "Salir",
  next: "Siguiente",
  complete: "Completar",
  step: "Paso",
  of: "de",
  "trade-executed": "¡Operación ejecutada!",
  "trade-closed": "Operación cerrada correctamente",
  "help-title": "Ayuda y Aprendizaje",
  "help-description": "¿Nuevo en forex? Mira nuestras guías y tutoriales para principiantes.",
  "search-help-placeholder": "Buscar artículos de ayuda...",
  "learning-guides": "Guías de Aprendizaje",
  "articles-label": "artículos",
  "beginner-trader": "Operador principiante",
  "search-placeholder": "Buscar pares de divisas...",
  "markets-open": "Mercados Abiertos",
  "language-tooltip": "Seleccionar idioma (English / Español)",
  "help-tooltip": "Obtener ayuda y tutoriales",
  "notifications-tooltip": "Notificaciones (próximamente)",
  "settings-tooltip": "Configuración (próximamente)",
  "switch-to-light": "Cambiar a modo claro",
  "switch-to-dark": "Cambiar a modo oscuro",
  "search-coming-soon-title": "La búsqueda llegará pronto",
  "search-coming-soon-desc": "Estamos trabajando en añadir búsqueda para pares de divisas.",
  "settings-coming-soon-title": "Configuración próximamente",
  "settings-coming-soon-desc": "Los ajustes del usuario estarán disponibles en la próxima actualización.",
  "notifications-coming-soon-title": "Notificaciones aún no disponibles",
  "notifications-coming-soon-desc": "La función de notificaciones en tiempo real está en desarrollo.",
  "welcome-back": "Bienvenido de nuevo, ",
  "your-trades": "Tus Operaciones",
  "trades-hover-headers": "Pasa el cursor sobre los encabezados para ver qué significan",
  "trades-active": "activas",
  "trades-empty-title": "Aún no hay operaciones",
  "trades-empty-desc": "Realiza tu primera operación de práctica para verla aquí",
  "trades-column-pair": "Par",
  "trades-column-direction": "Dirección",
  "trades-column-size": "Tamaño",
  "trades-column-entry": "Entrada",
  "trades-column-pnl": "Ganancia/Pérdida",
  "trades-column-status": "Estado",
  "trades-hint-pair": "Las dos divisas que se intercambian. EUR/USD significa operar euros contra dólares estadounidenses.",
  "trades-hint-direction": "COMPRAR = ganas cuando el precio SUBE. VENDER = ganas cuando el precio BAJA.",
  "trades-hint-size": "Cuánto estás operando. 0.01 lotes es el tamaño más pequeño, ideal para aprender.",
  "trades-hint-entry": "El precio al que comenzó tu operación.",
  "trades-hint-pnl": "Ganancia/Pérdida: verde significa que ganas dinero, rojo significa que pierdes.",
  "trades-hint-status": "Abierta = la operación sigue activa. Cerrada = la operación terminó.",
  "trades-direction-buy-hint": "Ganas si el precio sube",
  "trades-direction-sell-hint": "Ganas si el precio baja",
  "trades-lots": "lotes",
  "trades-status-open": "Activa",
  "trades-status-closed": "Cerrada",
  "trades-pnl-title": "Entendiendo Ganancia/Pérdida (Profit & Loss)",
  "trades-pnl-desc": "La ganancia/pérdida muestra cuánto has ganado o perdido en cada operación. Se calcula a partir de la diferencia entre tu precio de entrada y el precio actual, multiplicada por el tamaño de tu operación. Con 0.01 lotes, cada pip vale aproximadamente $0.10.",
}

export const translations: Record<Language, Record<string, string>> = {
  en: spanish,
  es: spanish,
  fr: spanish,
  de: spanish,
  it: spanish,
  pt: spanish,
  ja: spanish,
  zh: spanish,
  ru: spanish,
  ar: spanish,
}

export function translate(key: string, language: Language): string {
  return translations[language]?.[key] || translations.es[key] || key
}