export type Language = "en" | "es" | "fr" | "de" | "it" | "pt" | "ja" | "zh" | "ru" | "ar"

export const languageLabels: Record<Language, string> = {
  en: "Inglés",
  es: "Español",
  fr: "Francés",
  de: "Alemán",
  it: "Italiano",
  pt: "Portugués",
  ja: "Japonés",
  zh: "Chino",
  ru: "Ruso",
  ar: "Árabe",
}

const english: Record<string, string> = {
  dashboard: "Dashboard",
  trade: "Trade",
  markets: "Markets",
  history: "History",
  wallet: "Wallet",
  learn: "Learn",
  "hint-dashboard": "Your main trading overview",
  "hint-trade": "Open and manage trades",
  "hint-markets": "Browse all currency pairs",
  "hint-history": "View your past trades",
  "hint-wallet": "Manage your funds",
  "hint-learn": "Tutorials and guides",
  logout: "Logout",
  settings: "Settings",
  notifications: "Notifications",
  help: "Help",
  "coming-soon": "Coming soon",
  loading: "Loading...",
  "no-results": "No results found",
  "total-balance": "Total Balance",
  "total-profit": "Total Profit",
  "open-positions": "Open Positions",
  "available-margin": "Available Margin",
  "place-trade": "Place a Trade",
  "practice-mode": "Practice with virtual money",
  "practice-mode-desc": "You're trading with $1,000 virtual money. No real funds at risk - learn freely!",
  "currency-pair": "Currency Pair",
  "trade-size": "Trade Size (Lots)",
  buy: "BUY",
  sell: "SELL",
  "confirm-trade": "Confirm your trade",
  cancel: "Cancel",
  confirm: "Confirm",
  "start-learning": "Start your learning path",
  "learning-roadmap": "Learning Roadmap",
  "learning-roadmap-subtitle": "Master short lessons and practice",
  "learning-progress": "Progress",
  "learning-current": "Current",
  "learning-practice-preview": "Practice Preview",
  "learning-completed": "Completed",
  "learning-in-progress": "In progress",
  "learning-reviewed": "Lesson reviewed",
  "learning-pending": "Not yet practiced",
  "learning-focus": "Focus",
  "learning-open-lesson": "Open lesson",
  "learning-next-step": "Next step",
  "learning-next-step-copy": "Try a short practice trade after this lesson to reinforce learning.",
  "lesson-overview": "Lesson Overview",
  "history-log-title": "Your learning log",
  "history-log-desc": "We will list every completed trade with an easy summary.",
  "markets-popular-title": "Popular beginner pairs",
  "markets-popular-desc": "These pairs have reliable liquidity and clear patterns for practice.",
  "wallet-practice-title": "Practice balance",
  "wallet-practice-desc": "This is virtual money you can use to learn safely.",
  "learn-desc": "Follow one short lesson at a time and practice after each one.",
  "visual-example": "Visual example",
  "visual-doji": "A small body with balanced wicks shows indecision.",
  "visual-hammer": "A long lower wick shows rejection and possible reversal.",
  "visual-engulfing": "A larger candle fully covers the previous one.",
  "visual-context": "Confirm the pattern with trend and nearby levels.",
  "lesson.candlestick-patterns.steps.0.title": "The Doji Candle",
  "lesson.candlestick-patterns.steps.0.description": "A Doji candle has an open and close at nearly the same price, signaling indecision.",
  "lesson.candlestick-patterns.steps.0.action": "Open Markets and look for the Doji example card",
  "lesson.candlestick-patterns.steps.1.title": "Hammer and Hanging Man",
  "lesson.candlestick-patterns.steps.1.description": "A Hammer has a small body with a long lower wick and can signal a reversal. The Hanging Man is the bearish counterpart.",
  "lesson.candlestick-patterns.steps.1.action": "Practice identifying these patterns on historical charts",
  "lesson.candlestick-patterns.steps.2.title": "Engulfing Patterns",
  "lesson.candlestick-patterns.steps.2.description": "An engulfing pattern happens when a larger candle fully covers the previous one and can indicate a reversal.",
  "lesson.candlestick-patterns.steps.2.action": "Look for bullish and bearish engulfing patterns in your analysis",
  "lesson.candlestick-patterns.steps.3.title": "Using Patterns in Trading",
  "lesson.candlestick-patterns.steps.3.description": "Candlestick patterns are most reliable when combined with support/resistance and trend confirmation.",
  "lesson.candlestick-patterns.steps.3.action": "Before your next trade, identify a pattern and a key level to confirm entry",
  "getting-started": "Getting Started",
  "trading-basics": "Trading Basics",
  "simple-strategies": "Simple Strategies",
  "help.article.getting-started.0.title": "What is forex trading?",
  "help.article.getting-started.0.time": "3 min read",
  "help.article.getting-started.1.title": "Understanding currency pairs",
  "help.article.getting-started.1.time": "4 min read",
  "help.article.getting-started.2.title": "How to read a price chart",
  "help.article.getting-started.2.time": "5 min read",
  "help.article.getting-started.3.title": "Your first practice trade",
  "help.article.getting-started.3.time": "3 min read",
  "help.article.trading-basics.0.title": "What are pips and lots?",
  "help.article.trading-basics.0.time": "3 min read",
  "help.article.trading-basics.1.title": "Understanding leverage and margin",
  "help.article.trading-basics.1.time": "5 min read",
  "help.article.trading-basics.2.title": "Setting stop-loss and take-profit",
  "help.article.trading-basics.2.time": "4 min read",
  "help.article.trading-basics.3.title": "Market vs limit orders",
  "help.article.trading-basics.3.time": "3 min read",
  "help.article.strategies.0.title": "Trend following for beginners",
  "help.article.strategies.0.time": "6 min read",
  "help.article.strategies.1.title": "Support and resistance basics",
  "help.article.strategies.1.time": "5 min read",
  "help.article.strategies.2.title": "Risk management 101",
  "help.article.strategies.2.time": "4 min read",
  "faq.title": "Frequently Asked",
  "faq.q.0": "Is this real money?",
  "faq.a.0": "No! You're in practice mode with $1,000 virtual money. Nothing you do here costs real money.",
  "faq.q.1": "What does BUY and SELL mean?",
  "faq.a.1": "BUY (going 'long') means you profit when the price goes UP. SELL (going 'short') means you profit when the price goes DOWN.",
  "faq.q.2": "What's a safe lot size to start?",
  "faq.a.2": "Start with 0.01 lots (micro lot). This minimizes your risk while you learn how trading works.",
  "faq.q.3": "What is spread?",
  "faq.a.3": "The spread is the difference between the buy and sell price. It's essentially the broker's fee for each trade.",
  continue: "Continue",
  "lesson-not-found-title": "Lesson Not Found",
  "lesson-not-found-desc": "This lesson does not exist",
  "lesson-guided-subtitle": "Follow the guided tutorial",
  "back-to-lessons": "Back to Lessons",
  "start-guided-tutorial": "Start Guided Tutorial",
  exit: "Exit",
  next: "Next",
  complete: "Complete",
  step: "Step",
  of: "of",
  "trade-executed": "Trade executed!",
  "trade-closed": "Trade closed successfully",
  "help-title": "Help & Learning",
  "help-description": "New to forex? Check out our beginner guides and tutorials.",
  "search-help-placeholder": "Search help articles...",
  "learning-guides": "Learning Guides",
  "articles-label": "articles",
  "beginner-trader": "Beginner trader",
  "search-placeholder": "Search currency pairs...",
  "markets-open": "Markets Open",
  "language-tooltip": "Select language (English / Español)",
  "help-tooltip": "Get help & tutorials",
  "notifications-tooltip": "Notifications (coming soon)",
  "settings-tooltip": "Settings (coming soon)",
  "switch-to-light": "Switch to light mode",
  "switch-to-dark": "Switch to dark mode",
  "search-coming-soon-title": "Search is coming soon",
  "search-coming-soon-desc": "We're working on adding search functionality for currency pairs.",
  "settings-coming-soon-title": "Settings coming soon",
  "settings-coming-soon-desc": "User settings will be available in the next update.",
  "notifications-coming-soon-title": "Notifications not yet available",
  "notifications-coming-soon-desc": "Real-time notifications feature is under development.",
  "welcome-back": "Welcome back, ",
  "your-trades": "Your Trades",
  "trades-hover-headers": "Hover headers to learn what they mean",
  "trades-active": "active",
  "trades-empty-title": "No trades yet",
  "trades-empty-desc": "Place your first practice trade to see it here",
  "trades-column-pair": "Pair",
  "trades-column-direction": "Direction",
  "trades-column-size": "Size",
  "trades-column-entry": "Entry",
  "trades-column-pnl": "P&L",
  "trades-column-status": "Status",
  "trades-hint-pair": "The two currencies being exchanged. EUR/USD means trading Euros for US Dollars.",
  "trades-hint-direction": "BUY = you profit when price goes UP. SELL = you profit when price goes DOWN.",
  "trades-hint-size": "How much you're trading. 0.01 lots is the smallest — perfect for learning!",
  "trades-hint-entry": "The price when your trade started.",
  "trades-hint-pnl": "Profit & Loss — green means you're making money, red means losing.",
  "trades-hint-status": "Open = trade is still running. Closed = trade is finished.",
  "trades-direction-buy-hint": "You profit if the price goes UP",
  "trades-direction-sell-hint": "You profit if the price goes DOWN",
  "trades-lots": "lots",
  "trades-status-open": "Active",
  "trades-status-closed": "Closed",
  "trades-pnl-title": "Understanding P&L (Profit & Loss)",
  "trades-pnl-desc": "P&L shows how much you have gained or lost on each trade. It is calculated from the difference between your entry price and current price, multiplied by your trade size. With 0.01 lots, each pip is worth about $0.10.",
  "lesson.support-resistance.title": "Support and Resistance",
  "lesson.support-resistance.description": "Learn how to find price areas where the market tends to react.",
  "lesson.support-resistance.fullDescription":
    "Identify horizontal zones and levels where price has historically bounced or stalled. You'll learn how to judge strength and use these zones to filter entries and exits.",
  "lesson.support-resistance.steps.0.title": "What is Support?",
  "lesson.support-resistance.steps.0.description": "Support is a price area where buying interest tends to appear and stop declines.",
  "lesson.support-resistance.steps.0.action": "Mark zones where price bounced upwards at least twice",
  "lesson.support-resistance.steps.1.title": "What is Resistance?",
  "lesson.support-resistance.steps.1.description": "Resistance is where selling interest caps rallies and can reverse price.",
  "lesson.support-resistance.steps.1.action": "Identify recent highs where price retreated",
  "lesson.support-resistance.steps.2.title": "Strength of Levels",
  "lesson.support-resistance.steps.2.description": "Stronger levels have more tests and tighter rejection wicks; weak levels are touched once.",
  "lesson.support-resistance.steps.2.action": "Count how many times price tested a level to judge its strength",
  "lesson.support-resistance.steps.3.title": "Using Levels with Confirmation",
  "lesson.support-resistance.steps.3.description": "Combine levels with price action (candles) or volume to avoid false signals.",
  "lesson.support-resistance.steps.3.action": "Wait for a confirming candle or volume spike before acting",
  "lesson.lot-sizes.title": "Lot Sizes",
  "lesson.lot-sizes.description": "Understand how position size affects your risk and returns.",
  "lesson.lot-sizes.fullDescription":
    "Learn how lot sizes translate to real dollar risk. We'll cover micro, mini and standard lots and show simple calculations to size positions according to risk rules.",
  "lesson.lot-sizes.steps.0.title": "What is a Lot?",
  "lesson.lot-sizes.steps.0.description": "A lot is the standardized trade size: 0.01 is a micro lot, 0.1 is a mini, 1.0 is a standard lot.",
  "lesson.lot-sizes.steps.0.action": "Compare the pip value of 0.01 vs 0.1 vs 1.0 on a sample pair",
  "lesson.lot-sizes.steps.1.title": "Risk per Trade",
  "lesson.lot-sizes.steps.1.description": "Decide how much of your account you're willing to risk (e.g., 1% per trade) and convert that to lot size.",
  "lesson.lot-sizes.steps.1.action": "Calculate lot size for a $10 risk on a $1,000 account",
  "lesson.lot-sizes.steps.2.title": "Adjusting for Volatility",
  "lesson.lot-sizes.steps.2.description": "Higher volatility pairs require smaller lot sizes to keep risk similar.",
  "lesson.lot-sizes.steps.2.action": "Compare volatility across two pairs and reduce lot size for the more volatile one",
  "lesson.lot-sizes.steps.3.title": "Practical Exercise",
  "lesson.lot-sizes.steps.3.description": "Apply a fixed risk percent to multiple hypothetical trades to observe how lot sizes change.",
  "lesson.lot-sizes.steps.3.action": "Compute lot sizes for three trade ideas using a 1% risk rule",
}

const spanish: Record<string, string> = {
  dashboard: "Panel",
  trade: "Operar",
  markets: "Mercados",
  history: "Historial",
  wallet: "Cartera",
  learn: "Aprender",
  "hint-dashboard": "Tu vista general principal de trading",
  "hint-trade": "Abrir y gestionar operaciones",
  "hint-markets": "Explorar todos los pares de divisas",
  "hint-history": "Ver tus operaciones pasadas",
  "hint-wallet": "Gestionar tus fondos",
  "hint-learn": "Tutoriales y guías",
  logout: "Cerrar sesión",
  settings: "Configuración",
  notifications: "Notificaciones",
  help: "Ayuda",
  "coming-soon": "Próximamente",
  loading: "Cargando...",
  "no-results": "No se encontraron resultados",
  "total-balance": "Saldo Total",
  "total-profit": "Ganancia Total",
  "open-positions": "Posiciones Abiertas",
  "available-margin": "Margen Disponible",
  "place-trade": "Realizar una Operación",
  "practice-mode": "Practica con dinero virtual",
  "practice-mode-desc": "Estás operando con $1,000 virtuales. Sin fondos reales en riesgo - ¡aprende libremente!",
  "currency-pair": "Par de Divisas",
  "trade-size": "Tamaño de la Operación (Lotes)",
  buy: "COMPRAR",
  sell: "VENDER",
  "confirm-trade": "Confirmar tu operación",
  cancel: "Cancelar",
  confirm: "Confirmar",
  "start-learning": "Comienza tu camino de aprendizaje",
  "learning-roadmap": "Ruta de aprendizaje",
  "learning-roadmap-subtitle": "Domina lecciones cortas y practica",
  "learning-progress": "Progreso",
  "learning-current": "Actual",
  "learning-practice-preview": "Vista previa de práctica",
  "learning-completed": "Completado",
  "learning-in-progress": "En progreso",
  "learning-reviewed": "Lección revisada",
  "learning-pending": "Aún no practicada",
  "learning-focus": "Enfoque",
  "learning-open-lesson": "Abrir lección",
  "learning-next-step": "Siguiente paso",
  "learning-next-step-copy": "Prueba una operación de práctica corta después de esta lección para reforzar lo aprendido.",
  "lesson-overview": "Descripción de la Lección",
  "history-log-title": "Tu registro de aprendizaje",
  "history-log-desc": "Aquí listaremos cada operación completada con un resumen fácil de entender.",
  "markets-popular-title": "Pares populares para principiantes",
  "markets-popular-desc": "Estos pares tienen liquidez confiable y patrones claros para practicar.",
  "wallet-practice-title": "Saldo de práctica",
  "wallet-practice-desc": "Este es dinero virtual que puedes usar para aprender de forma segura.",
  "learn-desc": "Sigue una lección corta a la vez y practica después de cada una.",
  "visual-example": "Ejemplo visual",
  "visual-doji": "Un cuerpo pequeño con mechas equilibradas muestra indecisión.",
  "visual-hammer": "Una mecha inferior larga muestra rechazo y posible reversión.",
  "visual-engulfing": "Una vela más grande cubre por completo a la anterior.",
  "visual-context": "Confirma el patrón con la tendencia y los niveles cercanos.",
  "getting-started": "Comenzar",
  "trading-basics": "Conceptos Básicos",
  "simple-strategies": "Estrategias Simples",
  "help.article.getting-started.0.title": "¿Qué es el trading de forex?",
  "help.article.getting-started.0.time": "3 min",
  "help.article.getting-started.1.title": "Entendiendo los pares de divisas",
  "help.article.getting-started.1.time": "4 min",
  "help.article.getting-started.2.title": "Cómo leer un gráfico de precios",
  "help.article.getting-started.2.time": "5 min",
  "help.article.getting-started.3.title": "Tu primera operación de práctica",
  "help.article.getting-started.3.time": "3 min",
  "help.article.trading-basics.0.title": "¿Qué son los pips y los lotes?",
  "help.article.trading-basics.0.time": "3 min",
  "help.article.trading-basics.1.title": "Entendiendo apalancamiento y margen",
  "help.article.trading-basics.1.time": "5 min",
  "help.article.trading-basics.2.title": "Configurar stop-loss y take-profit",
  "help.article.trading-basics.2.time": "4 min",
  "help.article.trading-basics.3.title": "Ordenes de mercado vs límite",
  "help.article.trading-basics.3.time": "3 min",
  "help.article.strategies.0.title": "Seguir tendencias para principiantes",
  "help.article.strategies.0.time": "6 min",
  "help.article.strategies.1.title": "Conceptos básicos de soporte y resistencia",
  "help.article.strategies.1.time": "5 min",
  "help.article.strategies.2.title": "Gestión de riesgo 101",
  "help.article.strategies.2.time": "4 min",
  "faq.title": "Preguntas Frecuentes",
  "faq.q.0": "¿Es dinero real?",
  "faq.a.0": "No. Estás en modo práctica con $1,000 virtuales. Nada de lo que hagas aquí cuesta dinero real.",
  "faq.q.1": "¿Qué significan BUY y SELL?",
  "faq.a.1": "BUY (ir 'largo') significa que ganas cuando el precio SUBE. SELL (ir 'corto') significa que ganas cuando el precio BAJA.",
  "faq.q.2": "¿Qué tamaño de lote es seguro para empezar?",
  "faq.a.2": "Empieza con 0.01 lotes (micro lote). Esto minimiza el riesgo mientras aprendes cómo funciona el trading.",
  "faq.q.3": "¿Qué es el spread?",
  "faq.a.3": "El spread es la diferencia entre el precio de compra y de venta. Básicamente es la comisión del bróker por cada operación.",
  continue: "Continuar",
  "lesson.forex-basics.title": "Conceptos Básicos de Forex",
  "lesson.forex-basics.description": "Entiende cómo se mueven los pares de divisas.",
  "lesson.forex-basics.fullDescription":
    "En esta lección aprenderás los fundamentos del trading de forex, incluyendo pares de divisas, pips y cómo se mueven los precios en el mercado.",
  "lesson.forex-basics.steps.0.title": "¿Qué es Forex?",
  "lesson.forex-basics.steps.0.description":
    "Forex es el mercado de intercambio de divisas donde se compran y venden monedas. Cada operación implica comprar una divisa y vender otra, como EUR/USD.",
  "lesson.forex-basics.steps.0.action": "Haz clic en la sección Mercados para ver pares de divisas en vivo",
  "lesson.forex-basics.steps.1.title": "Explicación de Pares de Divisas",
  "lesson.forex-basics.steps.1.description":
    "Los pares de divisas siempre tienen dos partes: la divisa base (primera) y la divisa cotizada (segunda). Por ejemplo, en EUR/USD, EUR es la base y USD es la cotizada.",
  "lesson.forex-basics.steps.1.action": "Observa cómo cada precio muestra el formato base/cotizada",
  "lesson.forex-basics.steps.2.title": "Entendiendo los Pips",
  "lesson.forex-basics.steps.2.description":
    "Un pip es el movimiento mínimo de precio en forex. La mayoría de los pares se mueven en incrementos de 0.0001 (4 decimales). Un pip = 0.0001 para la mayoría de los pares.",
  "lesson.forex-basics.steps.2.action": "Mira cómo cambian los precios en pequeños incrementos durante el horario del mercado",
  "lesson.forex-basics.steps.3.title": "Precios Bid y Ask",
  "lesson.forex-basics.steps.3.description":
    "Cada cotización tiene un precio bid (lo que quieren los vendedores) y un precio ask (lo que quieren los compradores). Cuando compras, pagas el ask. Cuando vendes, recibes el bid.",
  "lesson.forex-basics.steps.3.action": "Recuerda: siempre compra al ask y vende al bid",
  "lesson.risk-control.title": "Control de Riesgo",
  "lesson.risk-control.description": "Aprende a proteger tu saldo.",
  "lesson.risk-control.fullDescription":
    "Descubre los principios esenciales de la gestión de riesgo para proteger tu cuenta de trading y maximizar la rentabilidad a largo plazo.",
  "lesson.risk-control.steps.0.title": "La Regla del 1%",
  "lesson.risk-control.steps.0.description":
    "Nunca arriesgues más del 1% del saldo de tu cuenta en una sola operación.",
  "lesson.risk-control.steps.0.action": "Calcula: si tienes $1,000, no arriesgues más de $10 por operación",
  "lesson.risk-control.steps.1.title": "Tamaño de Lote",
  "lesson.risk-control.steps.1.description":
    "El tamaño de tu lote determina cuánto dinero está en riesgo. Empieza con 0.01 lotes.",
  "lesson.risk-control.steps.1.action": "Prueba una operación de 0.01 lotes para ver cómo se calcula el riesgo",
  "lesson.risk-control.steps.2.title": "Órdenes Stop Loss",
  "lesson.risk-control.steps.2.description":
    "Siempre establece un stop loss antes de entrar en una operación. Esto cierra tu posición automáticamente si el precio se mueve en tu contra más allá de tu tolerancia al riesgo.",
  "lesson.risk-control.steps.2.action": "En la sección Operar, revisa el campo stop loss antes de ejecutar",
  "lesson.risk-control.steps.3.title": "Relación Riesgo/Recompensa",
  "lesson.risk-control.steps.3.description":
    "Apunta a una relación riesgo/recompensa de 1:2 o mejor.",
  "lesson.risk-control.steps.3.action": "Planifica tus operaciones con buena relación riesgo/recompensa antes de entrar",
  "lesson.reading-charts.title": "Leer Gráficos",
  "lesson.reading-charts.description": "Aprende a leer gráficos de precio paso a paso para reconocer tendencias y puntos de oportunidad.",
  "lesson.reading-charts.fullDescription":
    "Este módulo te enseña a interpretar velas, patrones y volúmenes: cómo identificar una tendencia, dónde buscar señales de reversión y cómo confirmar entradas con evidencia visual clara.",
  "lesson.reading-charts.steps.0.title": "Qué muestra una vela (OHLC)",
  "lesson.reading-charts.steps.0.description":
    "Cada vela muestra: apertura, máximo, mínimo y cierre. Aprende a leer la información básica de una vela y qué significa en contexto.",
  "lesson.reading-charts.steps.0.action": "Identifica la apertura y el cierre en varias velas y anota si el cierre está por encima o por debajo de la apertura",
  "lesson.reading-charts.steps.1.title": "Cómo identificar una tendencia",
  "lesson.reading-charts.steps.1.description":
    "Una tendencia alcista forma máximos y mínimos crecientes; una bajista forma máximos y mínimos decrecientes. Esto te ayuda a alinear tus operaciones con la dirección del mercado.",
  "lesson.reading-charts.steps.1.action": "Marca al menos dos máximos y dos mínimos para decidir si la tendencia es clara",
  "lesson.reading-charts.steps.2.title": "Soporte y Resistencia (práctico)",
  "lesson.reading-charts.steps.2.description":
    "El soporte es un área donde el precio suele rebotar hacia arriba; la resistencia es donde suele revertir hacia abajo. Aprenderás a dibujar estas zonas y a usarlas como filtros de entrada.",
  "lesson.reading-charts.steps.2.action": "Traza las zonas donde el precio ha rebotado al menos 2 veces en el pasado reciente",
  "lesson.reading-charts.steps.3.title": "Patrones de Velas (introducción)",
  "lesson.reading-charts.steps.3.description":
    "Ciertas formaciones de velas pueden indicar indecisión, reversión o continuación. Este paso te muestra señales comunes y cómo validarlas con otros indicadores.",
  "lesson.reading-charts.steps.3.action": "Encuentra una vela destacada y pregunta: ¿confirma la tendencia o sugiere un cambio?",
  "lesson.candlestick-patterns.steps.0.title": "La Vela Doji",
  "lesson.candlestick-patterns.steps.0.description": "Una Doji tiene apertura y cierre casi iguales, indicando indecisión.",
  "lesson.candlestick-patterns.steps.0.action": "Abre Mercados y busca la tarjeta de ejemplo Doji",
  "lesson.candlestick-patterns.steps.1.title": "Hammer y Hanging Man",
  "lesson.candlestick-patterns.steps.1.description": "El Hammer puede señalar reversión de bajista a alcista. El Hanging Man es la versión bajista.",
  "lesson.candlestick-patterns.steps.1.action": "Practica identificar estos patrones en gráficos históricos",
  "lesson.candlestick-patterns.steps.2.title": "Patrones Engulfing",
  "lesson.candlestick-patterns.steps.2.description": "Un engulfing alcista tiene una vela pequeña seguida por otra mayor que la cubre, indicando posible reversión.",
  "lesson.candlestick-patterns.steps.2.action": "Busca patrones engulfing alcistas y bajistas en tus análisis",
  "lesson.candlestick-patterns.steps.3.title": "Usar Patrones en Trading",
  "lesson.candlestick-patterns.steps.3.description": "Combina patrones con soporte/resistencia y la tendencia para mayor fiabilidad.",
  "lesson.candlestick-patterns.steps.3.action": "Antes de tu próxima operación, identifica un patrón y un nivel clave para confirmar la entrada",
  "lesson.candlestick-patterns.title": "Patrones de Velas",
  "lesson.candlestick-patterns.description": "Aprende a reconocer señales claras de acción del precio usando velas y combinándolas con niveles clave.",
  "lesson.candlestick-patterns.fullDescription":
    "Los patrones de velas reflejan la tensión entre compradores y vendedores. Aquí verás cómo identificar señales fiables, distinguir falsos positivos y confirmar con niveles y volumen.",
  "lesson.support-resistance.title": "Soporte y Resistencia",
  "lesson.support-resistance.description": "Identifica zonas donde el precio suele reaccionar y aprende a usarlas para filtrar entradas.",
  "lesson.support-resistance.fullDescription":
    "Aprenderás a dibujar zonas que han sido testeadas por el mercado, cómo distinguir un nivel fuerte de uno débil y cómo usar confirmaciones para aumentar la probabilidad de tus operaciones.",
  "lesson.lot-sizes.title": "Tamaños de Lote",
  "lesson.lot-sizes.description": "Controla el tamaño de tu posición.",
  "lesson.lot-sizes.fullDescription":
    "Descubre cómo el tamaño del lote afecta tu riesgo, exposición y consistencia al operar.",
  "lesson.support-resistance.steps.0.title": "¿Qué es Soporte?",
  "lesson.support-resistance.steps.0.description": "El soporte es un área donde suele aparecer demanda y detener caídas de precio.",
  "lesson.support-resistance.steps.0.action": "Marca zonas donde el precio rebotó hacia arriba al menos 2 veces",
  "lesson.support-resistance.steps.1.title": "¿Qué es Resistencia?",
  "lesson.support-resistance.steps.1.description": "La resistencia es donde la oferta frena los impulsos alcistas y puede revertir el precio.",
  "lesson.support-resistance.steps.1.action": "Identifica máximos recientes donde el precio retrocedió",
  "lesson.support-resistance.steps.2.title": "Fuerza de un nivel",
  "lesson.support-resistance.steps.2.description": "Los niveles fuertes son probados varias veces y muestran mechas claras de rechazo; los débiles son tocados una sola vez.",
  "lesson.support-resistance.steps.2.action": "Cuenta cuántas veces se testea una zona para juzgar su fuerza",
  "lesson.support-resistance.steps.3.title": "Confirmar con precio/volumen",
  "lesson.support-resistance.steps.3.description": "Combina niveles con velas de confirmación o aumentos de volumen para evitar señales falsas.",
  "lesson.support-resistance.steps.3.action": "Espera una vela de confirmación o un pico de volumen antes de actuar",
  "lesson.lot-sizes.steps.0.title": "¿Qué es un lote?",
  "lesson.lot-sizes.steps.0.description": "Un lote es el tamaño estándar de la operación: 0.01 micro, 0.1 mini, 1.0 estándar.",
  "lesson.lot-sizes.steps.0.action": "Compara el valor por pip de 0.01 vs 0.1 vs 1.0 en un par de ejemplo",
  "lesson.lot-sizes.steps.1.title": "Riesgo por operación",
  "lesson.lot-sizes.steps.1.description": "Decide cuánto de tu cuenta arriesgarás (ej. 1%) y convierte eso a tamaño de lote.",
  "lesson.lot-sizes.steps.1.action": "Calcula el lote para un riesgo de $10 en una cuenta de $1,000",
  "lesson.lot-sizes.steps.2.title": "Ajustar por volatilidad",
  "lesson.lot-sizes.steps.2.description": "Los pares más volátiles requieren lotes menores para mantener el mismo riesgo.",
  "lesson.lot-sizes.steps.2.action": "Compara la volatilidad entre dos pares y reduce el lote para el más volátil",
  "lesson.lot-sizes.steps.3.title": "Ejercicio práctico",
  "lesson.lot-sizes.steps.3.description": "Aplica un porcentaje de riesgo a varias ideas de trade para ver cómo cambian los tamaños.",
  "lesson.lot-sizes.steps.3.action": "Calcula lotes para tres ideas de trade usando la regla de 1%",
  "lesson-not-found-title": "Lección No Encontrada",
  "lesson-not-found-desc": "Esta lección no existe",
  "lesson-guided-subtitle": "Sigue el tutorial guiado",
  "back-to-lessons": "Volver a Lecciones",
  "start-guided-tutorial": "Iniciar Tutorial Guiado",
  exit: "Salir",
  next: "Siguiente",
  complete: "Completar",
  step: "Paso",
  of: "de",
  "trade-executed": "¡Operación ejecutada!",
  "trade-closed": "Operación cerrada correctamente",
  "help-title": "Ayuda y Aprendizaje",
  "help-description": "¿Nuevo en forex? Mira nuestras guías y tutoriales para principiantes.",
  "search-help-placeholder": "Buscar artículos de ayuda...",
  "learning-guides": "Guías de Aprendizaje",
  "articles-label": "artículos",
  "beginner-trader": "Operador principiante",
  "search-placeholder": "Buscar pares de divisas...",
  "markets-open": "Mercados Abiertos",
  "language-tooltip": "Seleccionar idioma (English / Español)",
  "help-tooltip": "Obtener ayuda y tutoriales",
  "notifications-tooltip": "Notificaciones (próximamente)",
  "settings-tooltip": "Configuración (próximamente)",
  "switch-to-light": "Cambiar a modo claro",
  "switch-to-dark": "Cambiar a modo oscuro",
  "search-coming-soon-title": "La búsqueda llegará pronto",
  "search-coming-soon-desc": "Estamos trabajando en añadir búsqueda para pares de divisas.",
  "settings-coming-soon-title": "Configuración próximamente",
  "settings-coming-soon-desc": "Los ajustes del usuario estarán disponibles en la próxima actualización.",
  "notifications-coming-soon-title": "Notificaciones aún no disponibles",
  "notifications-coming-soon-desc": "La función de notificaciones en tiempo real está en desarrollo.",
  "welcome-back": "Bienvenido de nuevo, ",
  "your-trades": "Tus Operaciones",
  "trades-hover-headers": "Pasa el cursor sobre los encabezados para ver qué significan",
  "trades-active": "activas",
  "trades-empty-title": "Aún no hay operaciones",
  "trades-empty-desc": "Realiza tu primera operación de práctica para verla aquí",
  "trades-column-pair": "Par",
  "trades-column-direction": "Dirección",
  "trades-column-size": "Tamaño",
  "trades-column-entry": "Entrada",
  "trades-column-pnl": "Ganancia/Pérdida",
  "trades-column-status": "Estado",
  "trades-hint-pair": "Las dos divisas que se intercambian. EUR/USD significa operar euros contra dólares estadounidenses.",
  "trades-hint-direction": "COMPRAR = ganas cuando el precio SUBE. VENDER = ganas cuando el precio BAJA.",
  "trades-hint-size": "Cuánto estás operando. 0.01 lotes es el tamaño más pequeño, ideal para aprender.",
  "trades-hint-entry": "El precio al que comenzó tu operación.",
  "trades-hint-pnl": "Ganancia/Pérdida: verde significa que ganas dinero, rojo significa que pierdes.",
  "trades-hint-status": "Abierta = la operación sigue activa. Cerrada = la operación terminó.",
  "trades-direction-buy-hint": "Ganas si el precio sube",
  "trades-direction-sell-hint": "Ganas si el precio baja",
  "trades-lots": "lotes",
  "trades-status-open": "Activa",
  "trades-status-closed": "Cerrada",
  "trades-pnl-title": "Entendiendo Ganancia/Pérdida (Profit & Loss)",
  "trades-pnl-desc": "La ganancia/pérdida muestra cuánto has ganado o perdido en cada operación. Se calcula a partir de la diferencia entre tu precio de entrada y el precio actual, multiplicada por el tamaño de tu operación. Con 0.01 lotes, cada pip vale aproximadamente $0.10.",
}

export const translations: Record<Language, Record<string, string>> = {
  en: spanish,
  es: spanish,
  fr: spanish,
  de: spanish,
  it: spanish,
  pt: spanish,
  ja: spanish,
  zh: spanish,
  ru: spanish,
  ar: spanish,
}

export function translate(key: string, language: Language): string {
  return translations[language]?.[key] || translations.es[key] || key
}